name: Docker Image CI

on:
  push:
    branches: [ "docker" ]
  pull_request:
    branches: [ "docker" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout repository
      
    - name: docker login
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: docker build java
      run: docker build --file demoPod/Dockerfile demoPod --tag darkmtrance/demopod:v2
    - name: docker push
      run: |
        docker push darkmtrance/demopod:v2
