name: Docker Image CI

on:
  push:
    branches: [ "java" ]
  pull_request:
    branches: [ "java" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker build java
      run: docker build ./demoPod --file Dockerfile --tag darkmtrance/demoPod:$(date +%s)
    - name: docker push
      run: |
        docker push darkmtrance/demoPod:$(date +%s)
