name: Docker Image CI Basic

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout repository
      
    - name: docker login
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: docker build
      run: docker build --file docker/Dockerfile docker --tag darkmtrance/hola-docker:indra3
    - name: docker push
      run: |
        docker push darkmtrance/hola-docker:indra3
